### ISSUE TITLE
How to get

### ISSUE THREAD

**Issue by chenxinghao** [dropbox/pyston#1065]

**Comment by chenxinghao** [comment]
How to get llvm IR file.ll?

**Comment by undingen** [comment]
I don't think we have a flag to directly output the LLVM IR to a file but you can pass -vv to print it to screen (with some additional debug information) or you add the code to print it to a file. But we only use LLVM in our highest tier so you will have to pass -n too to disable the interpreter and the baseline jit. And the IR is not very useful on it's own because it is highly dependent on the pyston runtime functions.
We also have a chat at https://gitter.im/dropbox/pyston which maybe easier to discuss followup questions.
