### ISSUE TITLE
Cleanup cython patch and upstream the required changes

### ISSUE THREAD

**Issue by undingen** [dropbox/pyston#1213]
Currently we required to apply a patch to cython 0.22 to get it to work.
We should update and cleanup the patch and upstream changes to cython in order to be able to use a unmodified version in the future.

**Comment by Daetalus** [comment]
The Pyston Cython changes was merged to Cython upstream: https://github.com/cython/cython/pull/528

Keep this issue open because the Cython test suite still can't passed fully. Maybe we need to submit more commits to Cython upstream in future. Anyway, Pyston can use Cython master branch(the time that PR got merged) to build NumPy, SciPy, Scikit-learn, lxml now.

**Comment by undingen** [comment]
cool, thanks this is awesome! :+1:

**Comment by kmod** [comment]
Awesome!
