### ISSUE TITLE
Cython access PyFrameObject directly

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#1238]
In Cython, it will access `PyFrameObject`'s member directly under `IF_CPYTHON`, like this:

```
#else
        // Generators always return to their most recent caller, not
        // necessarily their creator.
        if (self->exc_traceback) {
            PyTracebackObject *tb = (PyTracebackObject *) self->exc_traceback;
            PyFrameObject *f = tb->tb_frame;

            Py_XINCREF($local_tstate_cname->frame);
            assert(f->f_back == NULL);
            f->f_back = $local_tstate_cname->frame;
        }
#endif
```

And:

```
#else
        // Don't keep the reference to f_back any longer than necessary.  It
        // may keep a chain of frames alive or it could create a reference
        // cycle.
        if (self->exc_traceback) {
            PyTracebackObject *tb = (PyTracebackObject *) self->exc_traceback;
            PyFrameObject *f = tb->tb_frame;
            Py_CLEAR(f->f_back);
#endif
```

How to do it in Pyston? Should we add code like this?

```
BoxedFrame* f = tb->tb_frame;
f->clear();
// or Py_CLEAR(f->back());
```

@undingen 

For references, here is the original code:
https://github.com/cython/cython/blob/master/Cython/Utility/Coroutine.c#L483
https://github.com/cython/cython/blob/master/Cython/Utility/Coroutine.c#L510

**Comment by undingen** [comment]
At first I wanted to write that I think this is hard to support but now I'm not sure anymore :stuck_out_tongue_winking_eye: .
Maybe all we need is a `PyFrame_SetFrame` and use it instead of the direct access. 
`f->f_back = $local_tstate_cname->frame;` would become `PyFrame_SetFrame(f, $local_tstate_cname->frame)` and `Py_CLEAR(f->f_back);` would become `PyFrame_SetFrame(f, NULL)` and internally it would just set `BoxedFrame::_back` and do the refcounting ops.
Do you have a test where you can quickly see if this works or not? It could work or not I'm really not sure currently :-D
I guess if it does not work we can skip it for now like the pypy path does.

**Comment by Daetalus** [comment]
Cython call the members of PyFrameObject directly in some places. Note it here as a reminder:
- https://github.com/Daetalus/cython/commit/9d0fff29d26f6d9aa2f251a3402db4e0b9c6a0b3#diff-257bd2c96ac9690317fe6eac64f48603R1417
The changes in
- Cython/Utility/Coroutine.c
- Cython/Utility/Exceptions.c
in this commit: - https://github.com/Daetalus/cython/commit/9d0fff29d26f6d9aa2f251a3402db4e0b9c6a0b3

For now, just use PyPy path. 

I think this is related with https://github.com/dropbox/pyston/issues/1228

**Comment by Daetalus** [comment]
Closed this issue because we add Pyston support to Cython since Cython 0.25. https://github.com/cython/cython/pull/528

Cython then will use `__Pyx_PyFrame_SetLineNumber` to access line number. And in other places, Cython continue to use PyPy path.
