### ISSUE TITLE
Cython try to access PyCodeObject's member.

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#1241]
In Cython, `PyCode_GetNumFree((PyCodeObject *)o)` will get the `PyObject *co_freevars` member eventually. But Pyston use `BoxedCode` instead `PyCodeObject`, and `BoxedCode` does not have that member. Maybe we need to add that member and add `IF_PYTON` directive to let Cython access that member by use a function?

Reference
https://github.com/Daetalus/cython/commit/9d0fff29d26f6d9aa2f251a3402db4e0b9c6a0b3#diff-b68ea089583bb1818ad9a4fb39c5d534R118

**Comment by kmod** [comment]
We don't currently directly track the number of free variables, but I think we can replace their check with this function:
```C++
void PyCode_HasFreeVars(BoxedCode* code) {
  return code->source->getScopeInfo()->takesClosure();
}
```

Internally, takesClosure() adds up the number of free variables, so we could just expose that as well.  I'd want to test that more thoroughly if we go that route, though, since I think there's more room for small disagreements.

**Comment by Daetalus** [comment]
Close it via commit https://github.com/dropbox/pyston/pull/1251/commits/4989639e3f6d408d6f49dc77f0218be68eb17c6f, which added `PyCode_HasFreeVars` API.
