### ISSUE TITLE
make failure

### ISSUE THREAD

**Issue by dorafmon** [dropbox/pyston#265]
I haven't been building the master branch for a bit and today I tried to catch up. But when I do ``make all -j4`` I got error (after about half an hour):
```
make[3]: *** No rule to make target '/home/bobfang/pyston_deps/llvm-trunk-
build/Release/lib@LLVM_LIBDIR_SUFFIX@/libLLVMLTO.a', needed by 
'/home/bobfang/pyston_deps/llvm-trunk-build/Release/lib/libLTO.so'.  Stop.
```

Do you know how to solve this? Should I abandon ``make`` and migrate to ``cmake`` sometime?

**Comment by kmod** [comment]
Erf I was hoping that no one else would run into this issue, but I guess it needs to be addressed.  I haven't looked into it to figure out the exact reason, but there's some amount of bad dependency management happening and we're missing the (new) LLVM build step that sets LLVM_LIBDIR_SUFFIX.

As a workaround, just do `make llvm_allclean`.  You'll only have to do this on machines where you had run `make` prior to the latest LLVM rebase.

You should definitely switch to cmake!  It wouldn't have completely helped here since cmake doesn't update llvm revisions itself (@dagar is this planned / is it in one of the PRs I've been procastinating?).  In your particular case, by running `make` you will have updated the llvm revision already so cmake should be able to proceed.

**Comment by dagar** [comment]
No PRs yet, but what I presented in issue #241 (llvm and clang as git submodules) would prevent this. Your llvm_patches would live in an llvm github fork and cmake would have a dependency to keep the submodules up to date.

**Comment by dorafmon** [comment]
Hi sorry for not getting back sooner, I was busy with my exams. Yeah by recompiling LLVM it works now. I will close this issue. Thanks a lot.
