### ISSUE TITLE
sys_argv is (slightly) wrong

### ISSUE THREAD

**Issue by tjhance** [dropbox/pyston#385]
Expected:
['./test/tests/sys_argv.py']

Actual:
['/home/tjhance/pyston/./test/tests/sys_argv.py']

**Comment by tjhance** [comment]
This effects tracebacks as well:

```
-  File "./test/tests/generator_tracebacks.py", line 46, in <module>
+  File "/home/tjhance/pyston/./test/tests/generator_tracebacks.py", line 46, in <module>
```

**Comment by kmod** [comment]
Erf I was hoping to get away with this but I guess I can't :)  This is happening because of the change to the tester to run everything in a temporary directory; the sys_argv test is sensitive to this and changed output.  But the "cache the CPython output" code didn't know about this, so it kept the CPython cache but generated the new Pyston output and you get this error.  If you do `make clean` (or just `rm test/tests/generator_tracebacks.expected_cache`) this should go away.

Or rebase to https://github.com/dropbox/pyston/commit/c88e3b48d626bfac86a8c91bc9f5ab1cc86e67af, which should hopefully address this more systematically by invalidating the cache any time tester.py changes.  Hopefully this doesn't invalidate the cache too often...

**Comment by tjhance** [comment]
Yeah clearing the cache fixed it. Thanks!
