### ISSUE TITLE
I can not get the right LLVM IR when running "./pyston -Snvv add.py". Why?

### ISSUE THREAD

**Issue by lanyuesl** [dropbox/pyston#863]
Here is my source code:

def add_config_header():
 a=1
 b=2
 c=a+b
 print c

And here is the LLVM IR when I running pyston. It seems that the IR has nothing to do with my source code. Why?

 %frame_info = alloca %"struct.pyston::FrameInfo"
  %scratch = alloca i8, i64 152
  %0 = getelementptr inbounds %"struct.pyston::FrameInfo"* %frame_info, i32 0, i32 0
  %1 = getelementptr inbounds %"struct.pyston::ExcInfo"* %0, i32 0, i32 0
  store %"class.pyston::Box"* null, %"class.pyston::Box"** %1
  %2 = getelementptr inbounds %"struct.pyston::FrameInfo"* %frame_info, i32 0, i32 1
  store %"class.pyston::Box"* null, %"class.pyston::Box"** %2
  %3 = getelementptr inbounds %"struct.pyston::FrameInfo"* %frame_info, i32 0, i32 2
  store %"class.pyston::BoxedFrame"* null, %"class.pyston::BoxedFrame"** %3
  call void (i64, i32, i8*, i32, ...)* @llvm.experimental.patchpoint.void(i64 0, i32 95, i8* inttoptr (i64 -1 to i8*), i32 0, i8* %scratch, %"struct.pyston::FrameInfo"* %frame_info, i64 ptrtoint (i8* @c0 to i64))
  %4 = call %"class.pyston::Box"* inttoptr (i64 20379472 to %"class.pyston::Box"* (%"class.pyston::CLFunction"*, %"class.pyston::BoxedClosure"*, %"class.pyston::Box"*, %"class.pyston::Box"**, i64)*)(%"class.pyston::CLFunction"* @c1, %"class.pyston::BoxedClosure"* null, %"class.pyston::Box"* null, %"class.pyston::Box"** null, i64 0), !dbg !7
  call void (i64, i32, i8*, i32, ...)* @llvm.experimental.patchpoint.void(i64 1, i32 1119, i8* inttoptr (i64 -1 to i8*), i32 3, %"class.pyston::Box"* @cParentModule, %"class.pyston::BoxedString"* @c3, %"class.pyston::Box"* %4, i8* %scratch, %"struct.pyston::FrameInfo"* %frame_info, i64 ptrtoint (i8* @c4 to i64)), !dbg !7
  ret %"class.pyston::Box"* @cNone, !dbg !7

**Comment by kmod** [comment]
Unfortunately this is a bit hard to read without some of the surrounding context (also fyi, you can use three backticks (\`\`\`) to format something as a code block), but I think what's going on is that you are getting the IR for the module scope, not for the function.  This IR creates function object `%4`, stores it into the module object, and then returns None.  We lazy-create the IR, so if you add a call to your function you should see its IR get spewed out.

**Comment by lanyuesl** [comment]
So you mean that I can not get the LLVM IR of my python function with pyston?

**Comment by kmod** [comment]
If you call your function you will see the llvm IR :)  We could have the ability to create+display the llvm IR for a function without executing it, but we don't currently have that.  Also the IR will usually be tied to the types of the arguments that you pass it, so it's not quite the case that there's a single "the LLVM IR" for a python function.

I'm not sure how much this will help you though, since our IR is highly coupled with our runtime.  The IR we generate is only a small part of the semantics of a program, and will usually consist of instructions of the form "please call this opaque function object".  It's a very different case from C/C++/Java.

**Comment by lanyuesl** [comment]
thanks kmod
If I can use pyston to translate source code:
```
def add_config_header():
a=1
b=2
c=a+b
print c
```
to IR : 
```
void define add_config_header
entry:
%0=i32 1; %b = alloca i32;store i32 %b, i32 %0;
%1=i32 2;%a=alloca i32;store i32 %a, i32 %1;
%3= load i32 %b;%4=load i32 %c;
%5=add i32 %3, i32 %4;
%a= store i32 %5;

```
I would like to write code for that.

**Comment by undingen** [comment]
Because of pythons dynamic typing, frame introspection etc we will never be able to generate code like this. ok for you example we can do it but for everything more complicated the generated code will be full of patchpoints (inline caches) and guards because the types won't be fixed and than a generic int addition can't just be an llvm add instructions because of pythons automatic int to long conversion etc...
I'm not sure what you are exactly implementing but if you want to create a static python to some other language translator it will be a very hard task which will consume a lot of time. just translating on the LLVM IR level won't do it :-(.
